### PR TITLE
ENH: Add new sources

### LINKED ISSUE #5: Add new laser sources/destinations to UI
## Expected Behavior
We have all working laser sources supported via the GUI

## Current Behavior
We are missing LS3, LS4, LS5, and LD1 (relatively new additions). 

## Possible Solution
Figure out how to add them and do it. 

## Context
We're in the middle of updating the BTS during the summer down. This has included 3 new source lines. One destination line (the diagnostics line) was added during the previous spring/winter.

### LINKED ISSUE #6: Inconsistent Combo Box Behavior
## Expected Behavior
All the GUI elements behave identically

## Current Behavior
Two of the combo boxes for source destination are compressed for some reason. See the screenshot below. 

image

## Your Environment
This makes the target destination hard to read.

### LINKED ISSUE #10: Make Save Centroids Button More Easily Accessed
## Current Behavior
The "Save Centroids" button is only available when clicking the "motion" expert screen. This is kind of weird. 

## Possible Solution
Add to a camera specific screen, similar to the motion expert screen.

### PR DESCRIPTION
**Pull request by slactjohnson**
## Description
Adds new sources (LS3, LS4, and L6) to the GUI. 
Adds ability to show/hide the controls for each bay. 
Adds ability to show/hide the graphics panel for a smaller interface. 
Cleans up some small GUI issues. 

## Motivation and Context
Closes #5 
Closes #6 
Closes #10 

## How Has This Been Tested?
Tested using the live system in the laser hall. 

## Where Has This Been Documented?
This PR. 

## Screenshots:

image

image

### CODE REVIEW

**Comment by slactjohnson** [comment]
This is done, and functional, but waiting for more feedback from the laser group on anything they want to add.

**Comment by slactjohnson** [comment]
Modified btms-sources.ui to stop compressing the destination combo box.

**Comment by slactjohnson** [comment]
Updated to show save centroid button during expert mode: 
image

**Comment by slactjohnson** [comment]
I'd like to merge this before starting on the homing procedure work. I think there will be merge conflicts otherwise. This is ready for review.

**Comment by slactjohnson** [comment]
@christina-pino @aberges-SLAC Pinging here again. Please review when you get a chance.

**Comment by christina-pino** [comment]
Screenshot 2024-07-24 at 6 36 58 PM]
So far everything looks good and is functional (well without clicking any active buttons). One suggestion I have is to set the right side to be scrollable. The controls get very condensed when all of the sources are open. But this is a feature that can wait and be an issue for later.

**Review by christina-pino — DISMISSED** [review]
I added a comment on adding a scroll feature, but that can be a later improvement. Other than that, things look good and this is much better than before!

**Comment by slactjohnson** [comment]
@christina-pino That's a good idea. I've added a scroll bar to the GUI: 
image

**Comment by slactjohnson** [comment]
@christina-pino Sorry, re-requesting review; I added the scroll area you wanted and fixed an alignment issue with the left side sources.

**Review by christina-pino — APPROVED** [review]
Tested it out and all looks good. The scrollbar helps. Thanks for updating the screens!

**Pull request merged**
