### PR TITLE
ENH: Save nominal confirmation dialog

### LINKED ISSUE #3: Add acknowledgement GUI to all nominal position saves
## Current Behavior
When saving the nominal positions of a motor assembly in the BTPS/BTMS system, the positions are silently saved if you are within the nominal range of operation for a destination. This is in contrast to saving in the "unknown" position, where the system will respond with a prompt, so the users know that something is happening.

## Expected Behavior
Users would like acknowledgement that their positions were saved, regardless of if they are within nominal range or not.

## Context / environment
This created some uncertainty in the laser group about whether or not something was actually saved. Manual inspection showed that it was.

### LINKED ISSUE #7: Add acknowledgment GUI for Centroid position saves
## Expected Behavior
We probably want something similar to #3 for centroids

## Current Behavior
We don't have any acknowledgement

## Possible Solution
Copy-pasta the code from the motion position save function, or figure out a nice way to make one function that works for both.

### PR DESCRIPTION
**Pull request by slactjohnson**
## Description
Adds a confirmation dialog to the save nominal positions routine. 

## Motivation and Context
Closes #3 
Closes #7 

## How Has This Been Tested?
Tested live in the laser hall by saving current settings. Resulting dialogs below: 

image

image

### CODE REVIEW

**Review by aberges-SLAC — DISMISSED** [review]
Changes seem pretty straight forward to me. I'm a fan of using f-strings vs. implicit string concat with the old style substitutions, so I think it makes the `msg_str` easier to digest and maintain.

That's a 👍 from me

**Comment by slactjohnson** [comment]
@aberges-SLAC now that I've resolved the CI issues, can you give your approval again so I can merge?

**Comment by slactjohnson** [comment]
@aberges-SLAC Actually, scratch that, I'm just going to add the centroid nominal saving dialog to this PR as well.

**Comment by slactjohnson** [comment]
@aberges-SLAC @christina-pino this is ready for review again

**Review by aberges-SLAC — APPROVED** [review]
This looks good to me! 

I think I'm curious about what happens if any of the `config.device.property.nominal.get()` are called on a `config.device.nominal` that is empty, but my naive assumption is this just returns `Null` or `None` which gives you empty text in the display.

I'm sure you've already tested this and saw exactly that but I don't want to pass up an opportunity to learn a little more about this GUI.

Regardless, I'm approving because the logic is consistent and clean and you've demonstrated it working

**Comment by slactjohnson** [comment]
@aberges-SLAC These methods are ultimately reading PVs that come from the PLC. If a nominal setting has not been configured, we just get 0.0, like in the centroids example. If the PVs are not available, then it should throw an exception.

**Pull request merged**
